# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cats
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'
  pod 'lottie-ios', '~> 3.1.8'
  pod 'SwiftLint', '~> 0.40.0'
  pod 'SnapKit', '~> 5.0.0'
  
  target 'CatsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 3.0.0'
    pod 'Nimble', '~> 8.1.1'
    pod 'Nimble-Snapshots', '~> 8.2.1'
  end

end
