# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cats
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage'
  pod 'SwiftLint'
  
  target 'CatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
